# .taplo.toml
# Taplo formatter options: https://taplo.tamasfe.dev/configuration/formatter-options.html

[formatting]
# キーと値の間の = の周りの空白を省略するかどうか
compact_entries = false

# 複数行の配列に末尾のコンマを追加するかどうか
array_trailing_comma = true

# 配列が指定されたカラム幅を超えた場合に自動的に複数行に展開するかどうか
array_auto_expand = true

# 配列が1行に収まる場合に自動的に1行に折りたたむかどうか
array_auto_collapse = true

# エントリを垂直に整列するかどうか (例: '=' を揃える)
align_entries = false # デフォルトは false。true にすると = を揃える

# コメントを垂直に整列するかどうか
align_comments = true

# 最大行幅 (PrettierのprintWidthに相当)
column_width = 80

# インデントに使う文字列 (デフォルトはスペース2つ)
indent_string = "  "

# テーブル内のエントリをインデントするかどうか
indent_entries = false

# サブテーブルをインデントするかどうか
indent_tables = false

# キーをアルファベット順に並べ替えるかどうか (デフォルトは false)
# 注意: reorder_keys = true は、PrettierのjsonRecursiveSortに似た動作をTOMLで行います
reorder_keys = false

# 連続する空白行の最大数
allowed_blank_lines = 1

# ファイル末尾に改行を追加するかどうか
trailing_newline = true

# CRLF 改行コードを使用するかどうか (Windows向け)
crlf = false
