name: Hadolint

on:
  push:
    branches: [main, develop]
    paths:
      - "**/Dockerfile"
      - "**/Dockerfile.*"
      - ".hadolint.yaml"
  pull_request:
    branches: [main, develop]
    paths:
      - "**/Dockerfile"
      - "**/Dockerfile.*"
      - ".hadolint.yaml"

permissions:
  contents: read
  security-events: write

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: .devcontainer/Dockerfile
          config: .hadolint.yaml
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: hadolint-results.sarif
